version: "3.7"
services:

## --------------------------- marioCodelabs --------------------------- ##

  api:
    image: langgenius/dify-api:0.10.2 ## Versão do Dify 0.10.1

    volumes:
      - dify_storage:/app/api/storage

    networks:
      - interNET

    environment:
      ## Modo da execução
      - MODE=api

      ## Logs
      - LOG_LEVEL=INFO

      ## Secret Key
      - SECRET_KEY=d6a647aa0bda57742129502a137512dfwe

      ## Outras Url (vazio = mesmo do APP_WEB_URL)
      - CONSOLE_WEB_URL=
      - INIT_PASSWORD=
      - CONSOLE_API_URL=
      - SERVICE_API_URL=
      - FILES_URL=

      ## Url Dify
      - APP_WEB_URL=https://dify.domain.com

      ## Dados Postgres
      - MIGRATION_ENABLED=true
      - DB_USERNAME=postgres
      - DB_PASSWORD=VERIFICAR
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=dify

      ## Dados Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_USE_SSL=false
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/1

      ## Liberar acesso a todos os ip
      - WEB_API_CORS_ALLOW_ORIGINS=*
      - CONSOLE_CORS_ALLOW_ORIGINS=*

      ## Dados sobre armazenamento s3
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=storage
      - S3_ENDPOINT=s3.domain.com ## Url do s3 | Comente esta linha caso tiver erro ao fazer login
      - S3_BUCKET_NAME=dify
      - S3_ACCESS_KEY=VERIFICAR
      - S3_SECRET_KEY=VERIFICAR

      ## Configurações do Sandbox
      - CODE_EXECUTION_ENDPOINT=http://sandbox:8194
      - CODE_EXECUTION_API_KEY=f18fa0d66845cd7541fabc4226359887
      - CODE_MAX_NUMBER=9223372036854775807
      - CODE_MIN_NUMBER=-9223372036854775808
      - CODE_MAX_STRING_LENGTH=80000
      - TEMPLATE_TRANSFORM_MAX_LENGTH=80000
      - CODE_MAX_STRING_ARRAY_LENGTH=30
      - CODE_MAX_OBJECT_ARRAY_LENGTH=30
      - CODE_MAX_NUMBER_ARRAY_LENGTH=1000

      ## Dados Weaviate
      - VECTOR_STORE=weaviate
      - WEAVIATE_ENDPOINT=http://weaviate:8080
      - WEAVIATE_API_KEY=e6babe2ff41d34e0aff9c6e8af7f0f95
      - WEAVIATE_CLIENT_TIMEOUT=20

      ## Dados do Email
      - MAIL_TYPE=smtp
      - MAIL_DEFAULT_SEND_FROM=VERIFICAR
      - SMTP_SERVER=VERIFICAR
      - SMTP_PORT=587
      - SMTP_USERNAME=VERIFICAR
      - SMTP_PASSWORD=VERIFICAR

      ## Sentry
      - SENTRY_DSN=
      - SENTRY_TRACES_SAMPLE_RATE=1.0
      - SENTRY_PROFILES_SAMPLE_RATE=1.0

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M

## --------------------------- marioCodelabs --------------------------- ##

  worker:
    image: langgenius/dify-api:0.10.2 ## Versão do Dify 0.10.1

    volumes:
      - dify_storage:/app/api/storage

    networks:
      - interNET

    environment:
      ## Modo da execução
      - MODE=worker

      ## Logs
      - LOG_LEVEL=INFO
      
      ## Secret Key
      - SECRET_KEY=d6a647aa0bda57742129502a137512df

      ## Dados Postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=VERIFICAR
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=dify

      ## Dados Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_USE_SSL=false
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/1

      ## Dados Weaviate
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=storage
      - VECTOR_STORE=weaviate
      - WEAVIATE_ENDPOINT=http://weaviate:8080
      - WEAVIATE_API_KEY=e6babe2ff41d34e0aff9c6e8af7f0f95
      - WEAVIATE_CLIENT_TIMEOUT=20

      ## Dados do Email
      - MAIL_TYPE=smtp
      - MAIL_DEFAULT_SEND_FROM=VERIFICAR
      - SMTP_SERVER=VERIFICAR
      - SMTP_PORT=587
      - SMTP_USERNAME=VERIFICAR
      - SMTP_PASSWORD=VERIFICAR

    depends_on:
      - postgres
      - redis          
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager       
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- marioCodelabs --------------------------- ## 

  web:
    image: langgenius/dify-web:0.10.2 ## Versão do Dify 0.10.1

    networks:
      - interNET

    environment:
      ## Tipo da Edição
      - EDITION=SELF_HOSTED
      - CONSOLE_API_URL=

      ## Url Dify
      - APP_API_URL=https://dify.domain.com

      ## Sentry
      - SENTRY_DSN=

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- marioCodelabs --------------------------- ##

  sandbox:
    image: langgenius/dify-sandbox:0.2.10 # 0.2.10

    networks:
      - interNET
    
    environment:
      - API_KEY=f18fa0d66845cd7541fabc4226359887
      - GIN_MODE=release
      - WORKER_TIMEOUT=15

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- marioCodelabs --------------------------- ##

  weaviate:
    image: semitechnologies/weaviate:1.24.26 ## Versão do Weaviate 

    volumes:
      - dify_weaviate:/var/lib/weaviate

    networks:
      - interNET

    environment:
      ## Configurações Gerais
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1

      ## Dados de Autenticação
      - AUTHENTICATION_APIKEY_ENABLED=true
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=e6babe2ff41d34e0aff9c6e8af7f0f95
      - AUTHENTICATION_APIKEY_USERS=VERIFICAR
      - AUTHORIZATION_ADMINLIST_ENABLED=true
      - AUTHORIZATION_ADMINLIST_USERS=VERIFICAR

      ## Telemetria
      - DISABLE_TELEMETRY=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M

## --------------------------- ORION --------------------------- ##

  nginx:
    image: nginx:latest ## Versão do nginx
    entrypoint: ["sh", "-c", "chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh"]
    
    volumes:
      - /root/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - /root/nginx/proxy.conf.template:/etc/nginx/proxy.conf.template
      - /root/nginx/conf.d:/etc/nginx/conf.d
      - /root/nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - /root/nginx/ssl:/etc/ssl

    networks:
      - interNET

    environment:
      - NGINX_SSL_CERT_FILENAME=dify.crt
      - NGINX_SSL_CERT_KEY_FILENAME=dify.key
      - NGINX_SSL_PROTOCOLS=TLSv1.1 TLSv1.2 TLSv1.3
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_CLIENT_MAX_BODY_SIZE=15M
      - NGINX_KEEPALIVE_TIMEOUT=65
      - NGINX_PROXY_READ_TIMEOUT=3600s
      - NGINX_PROXY_SEND_TIMEOUT=3600s
      - NGINX_SERVER_NAME=_
      - NGINX_PORT=80

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.nginx.rule=Host(`dify.domain.com`) ## Url do Dify
        - traefik.http.routers.nginx.entrypoints=websecure
        - traefik.http.routers.nginx.tls.certresolver=letsencryptresolver
        - traefik.http.services.nginx.loadbalancer.server.port=80
        - traefik.http.services.nginx.loadbalancer.passHostHeader=true
        - traefik.http.routers.nginx.service=nginx

## --------------------------- marioCodelabs --------------------------- ##

volumes:
  dify_storage:
    external: true
    name: dify_storage
  dify_weaviate:
    external: true
    name: dify_weaviate

networks:
  interNET:
    external: true
    name: interNET
